### ISSUE TITLE
wetter_de script crashes

### ISSUE THREAD

**Issue by erensezener** [BCCN-Prog/weather_2016#1]
The logs are below @gkBCCN @inesw @clauslang 

[pcp2016@pcp2016 scripts]$ python html_extract.py 
Traceback (most recent call last):
  File "html_extract.py", line 21, in <module>
    urllib.request.urlretrieve(HOURLY_URL, FILE_BASE + DATE_TIME + '_' + city.split('-')[0] + '.html')
  File "/home/pcp2016/miniconda3/lib/python3.5/urllib/request.py", line 187, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/pcp2016/miniconda3/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/home/pcp2016/miniconda3/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/home/pcp2016/miniconda3/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/home/pcp2016/miniconda3/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/home/pcp2016/miniconda3/lib/python3.5/urllib/request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/pcp2016/miniconda3/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/home/pcp2016/miniconda3/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/home/pcp2016/miniconda3/lib/python3.5/http/client.py", line 1118, in _send_request
    self.putrequest(method, url, **skips)
  File "/home/pcp2016/miniconda3/lib/python3.5/http/client.py", line 960, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 30: ordinal not in range(128)

**Comment by gkBCCN** [comment]
Fixed: changed ü to ue.
