### ISSUE TITLE
Temperature missing in scraping database

### ISSUE THREAD

**Issue by clauslang** [BCCN-Prog/weather_2016#69]

**Comment by erensezener** [comment]
The databases created from the working scrapers are here https://drive.google.com/folderview?id=0BwQc_CC3arWWR2YyVURjdzctX3M&usp=sharing @gkBCCN @ge00rg

**Comment by erensezener** [comment]
The latest error: @gkBCCN 

```
Traceback (most recent call last):
  File "call_scrapers_wg.py", line 78, in <module>
    sc_wg(date_string, city, DATAPATH)
  File "/home/pcp2016/weather_2016/scraping/wunderground_api/wg_scraping.py", line 79, in scrape
    daily_db.save_dict(obj)
  File "/home/pcp2016/weather_2016/wrapper/DataWrapH5py.py", line 274, in save_dict
    self.add_data_point(**arg_dict)
TypeError: add_data_point() got an unexpected keyword argument 'temperature'
```
